name: klimatologiot
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.1.0

dependencies:
  app_settings: ^7.0.0
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.5
  cloud_firestore: ^6.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  equatable: ^2.0.5
  excel: ^4.0.6
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_database: ^12.1.3
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  flutter_localization: ^0.4.0
  google_fonts: ^8.0.2
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  monitoring_repository:
    path: packages/monitoring_repository
  path_provider: ^2.1.5
  pdf: ^3.11.1
  printing: ^5.13.1
  rxdart: ^0.27.7
  share_plus: ^13.1.0
  shared_preferences: ^2.5.5
  table_calendar: ^3.1.2
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: '#D3D3D3'
  image: images/logo_klimatologi.png

  android_12:
    image: images/logo_klimatologi.png
    color: '#D3D3D3'

  web: true

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'images/logo_klimatologi.png'
