// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZrk_k4DQ_ijCa6gp67oRklFMKD2dLcbQ',
    appId: '1:219079385989:web:5034585bf9dc1252a0daec',
    messagingSenderId: '219079385989',
    projectId: 'klimatologiot',
    authDomain: 'klimatologiot.firebaseapp.com',
    databaseURL: 'https://klimatologiot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'klimatologiot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN_9rnFxG99yficqRzTKJ7751D0GC0iXA',
    appId: '1:219079385989:android:1304b7433feb658ba0daec',
    messagingSenderId: '219079385989',
    projectId: 'klimatologiot',
    databaseURL: 'https://klimatologiot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'klimatologiot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1sRUSWC2nxONgcZ-zLMYr-tCHNPdVNT4',
    appId: '1:219079385989:ios:abf04f36d63bd3aaa0daec',
    messagingSenderId: '219079385989',
    projectId: 'klimatologiot',
    databaseURL: 'https://klimatologiot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'klimatologiot.firebasestorage.app',
    iosClientId: '219079385989-rrbf7b34t5rdvigs2l327qiheg357ogl.apps.googleusercontent.com',
    iosBundleId: 'com.example.klimatologiot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1sRUSWC2nxONgcZ-zLMYr-tCHNPdVNT4',
    appId: '1:219079385989:ios:abf04f36d63bd3aaa0daec',
    messagingSenderId: '219079385989',
    projectId: 'klimatologiot',
    databaseURL: 'https://klimatologiot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'klimatologiot.firebasestorage.app',
    iosClientId: '219079385989-rrbf7b34t5rdvigs2l327qiheg357ogl.apps.googleusercontent.com',
    iosBundleId: 'com.example.klimatologiot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZrk_k4DQ_ijCa6gp67oRklFMKD2dLcbQ',
    appId: '1:219079385989:web:3677e02c6b4f1ceca0daec',
    messagingSenderId: '219079385989',
    projectId: 'klimatologiot',
    authDomain: 'klimatologiot.firebaseapp.com',
    databaseURL: 'https://klimatologiot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'klimatologiot.firebasestorage.app',
  );
}
